#!/usr/bin/env python3
"""
build_data_v2.py — 以健保署 115.04.01 官方支付標準 CSV 為權威來源，
結合人工策劃的診所常用項目清單，產出新版 data/data.json。

用法：
    python3 scripts/build_data_v2.py
"""
from __future__ import annotations
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "A21030000I-D20021-001.csv"
OUT = ROOT / "data" / "data.json"

# ============================================================
# 策劃清單：code 對應 診所用途的補充 metadata
# name_zh / name_en / points / 備註 (→ notes 的基礎) 直接來自 CSV
# ============================================================

# eligibility 對照：
#   default  — 診斷符合 + 頻率在規定內即可申報
#   p4p      — 需加入該論質計酬計畫
#   cert     — 需醫師特定訓練認證
#   program  — 機構需與國健署簽約公費計畫
#   prior    — 需事前審查
# ------------------------------------------------------------

CURATED = [
    # ============== LAB — 生化：糖尿病 ==============
    {"code":"09005C", "cat":"lab", "sub":"生化 / 糖尿病",
     "aliases":["FBS", "Glucose AC", "空腹血糖", "AC Sugar"],
     "freq":"糖尿病追蹤 每月可 1 次；預防保健每年 1 次",
     "freq_days":30,
     "icd":["E10","E11","E13","E14","R73","Z13.1","O24"],
     "icd_desc":"糖尿病、血糖異常、妊娠糖尿病、成人預防保健"},
    {"code":"09140C", "cat":"lab", "sub":"生化 / 糖尿病",
     "aliases":["PC Sugar", "Glucose PC", "餐後血糖", "Postprandial glucose"],
     "freq":"糖尿病追蹤依臨床需要",
     "freq_days":30,
     "icd":["E10","E11","E13","E14","R73","O24"],
     "icd_desc":"糖尿病、血糖異常、妊娠糖尿病"},
    {"code":"09006C", "cat":"lab", "sub":"生化 / 糖尿病",
     "aliases":["HbA1c", "A1C", "糖化血色素", "HBA1C"],
     "freq":"糖尿病患每 3 個月 1 次為原則；每年至多 4 次",
     "freq_days":90,
     "icd":["E10","E11","E13","E14","O24"],
     "icd_desc":"第一/二型糖尿病、妊娠糖尿病",
     "clinical":"【重要】未確診糖尿病者不予給付。HPLC 法為主流。"},
    {"code":"09139C", "cat":"lab", "sub":"生化 / 糖尿病",
     "aliases":["GA", "Glycated Albumin", "糖化白蛋白"],
     "freq":"糖尿病追蹤替代 HbA1c，每 3 個月 1 次",
     "freq_days":90,
     "icd":["E10","E11","D58","D59","B18"],
     "icd_desc":"糖尿病合併溶血性貧血、慢性肝病等 HbA1c 不可信的狀況"},

    # ============== LAB — 生化：血脂 ==============
    {"code":"09001C", "cat":"lab", "sub":"生化 / 血脂",
     "aliases":["T-Cho", "TC", "Cholesterol", "總膽固醇", "膽固醇"],
     "freq":"高血脂治療 每 3-6 個月；未治療每年",
     "freq_days":90,
     "icd":["E78","I10","I11","I25","E11"],
     "icd_desc":"高血脂、高血壓、冠心病、糖尿病"},
    {"code":"09004C", "cat":"lab", "sub":"生化 / 血脂",
     "aliases":["TG", "Triglyceride", "三酸甘油脂", "三酸甘油酯"],
     "freq":"高血脂治療 每 3-6 個月；急性胰臟炎急性期",
     "freq_days":90,
     "icd":["E78","I10","I25","E11","K85","K86.1"],
     "icd_desc":"高血脂、冠心病、糖尿病、胰臟炎"},
    {"code":"09043C", "cat":"lab", "sub":"生化 / 血脂",
     "aliases":["HDL", "HDL-C", "高密度膽固醇", "好膽固醇"],
     "freq":"高血脂治療 每 3-6 個月",
     "freq_days":90,
     "icd":["E78","I10","I25","E11"],
     "icd_desc":"高血脂、冠心病、糖尿病"},
    {"code":"09044C", "cat":"lab", "sub":"生化 / 血脂",
     "aliases":["LDL", "LDL-C", "低密度膽固醇", "壞膽固醇"],
     "freq":"高血脂治療 每 3-6 個月；Statin 起始期較密",
     "freq_days":90,
     "icd":["E78","I10","I25","E11","G45","I63","I64"],
     "icd_desc":"高血脂、冠心病、糖尿病、腦中風",
     "clinical":"直接測定；TG<400 可由 Friedewald 計算。"},

    # ============== LAB — 生化：腎功能 ==============
    {"code":"09002C", "cat":"lab", "sub":"生化 / 腎功能",
     "aliases":["BUN", "Urea", "血中尿素氮", "尿素氮"],
     "freq":"慢性腎病追蹤 每 3-6 個月；用藥追蹤依需要",
     "freq_days":90,
     "icd":["N18","N19","N17","I10","E11","E14"],
     "icd_desc":"慢性腎病、AKI、高血壓、糖尿病腎病"},
    {"code":"09015C", "cat":"lab", "sub":"生化 / 腎功能",
     "aliases":["Cre", "Cr", "Creatinine", "肌酸酐", "血清肌酐"],
     "freq":"慢性腎病追蹤 每 3 個月；造影前後必做",
     "freq_days":90,
     "icd":["N18","N19","I10","E11","E14","N17"],
     "icd_desc":"腎功能評估、CKD 分期、AKI 追蹤、用藥劑量調整",
     "clinical":"eGFR 由 Cr + 年齡 + 性別計算 (CKD-EPI)。"},
    {"code":"09013C", "cat":"lab", "sub":"生化 / 代謝",
     "aliases":["UA", "Uric Acid", "尿酸", "Urate"],
     "freq":"痛風治療 每 3-6 個月",
     "freq_days":90,
     "icd":["M10","E79","N20","I10"],
     "icd_desc":"痛風、高尿酸血症、尿路結石",
     "clinical":"Allopurinol/Febuxostat 目標 UA<6 mg/dL (tophi<5)。"},

    # ============== LAB — 生化：電解質 / 礦物質 ==============
    {"code":"09021C", "cat":"lab", "sub":"生化 / 電解質",
     "aliases":["Na", "Sodium", "鈉"],
     "freq":"依臨床需要；利尿劑追蹤",
     "freq_days":90,
     "icd":["E87","I50","N18","F32"],
     "icd_desc":"電解質異常、心衰竭、腎病、脫水"},
    {"code":"09022C", "cat":"lab", "sub":"生化 / 電解質",
     "aliases":["K", "Potassium", "鉀"],
     "freq":"ACEI/ARB/MRA 追蹤每 3-6 個月；起始後 1-2 週",
     "freq_days":30,
     "icd":["E87.5","E87.6","I50","N18","E11"],
     "icd_desc":"高/低血鉀、心衰竭、腎病、RAAS 抑制劑"},
    {"code":"09023C", "cat":"lab", "sub":"生化 / 電解質",
     "aliases":["Cl", "Chloride", "氯"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["E87","N18","I50"],
     "icd_desc":"電解質異常、代謝性酸鹼失衡",
     "clinical":"用於計算 anion gap。"},
    {"code":"09011C", "cat":"lab", "sub":"生化 / 電解質",
     "aliases":["Ca", "Calcium", "鈣"],
     "freq":"CKD、骨病變、副甲狀腺疾病追蹤",
     "freq_days":90,
     "icd":["N18","E83.5","E21","M80","E55","E89"],
     "icd_desc":"CKD、鈣磷失衡、副甲狀腺病、骨質疏鬆、維生素 D 缺乏"},
    {"code":"09012C", "cat":"lab", "sub":"生化 / 電解質",
     "aliases":["P", "Phos", "Phosphate", "磷"],
     "freq":"CKD、副甲狀腺追蹤",
     "freq_days":90,
     "icd":["N18","E83.3","E21"],
     "icd_desc":"CKD、鈣磷失衡、副甲狀腺病"},

    # ============== LAB — 生化：肝功能 ==============
    {"code":"09025C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["AST", "GOT", "SGOT", "血清麩胺酸苯醋酸轉氨基脢"],
     "freq":"慢性肝病 每 3-6 個月；Statin 起始 3 個月",
     "freq_days":90,
     "icd":["B18","K70","K73","K76","E78"],
     "icd_desc":"慢性肝炎、脂肪肝、酒精性肝病、Statin 監測"},
    {"code":"09026C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["ALT", "GPT", "SGPT", "血清麩胺酸丙酮酸轉氨基脢"],
     "freq":"慢性肝病 每 3-6 個月",
     "freq_days":90,
     "icd":["B18","K70","K73","K76","E78"],
     "icd_desc":"慢性 B/C 肝、脂肪肝、酒精性肝病",
     "clinical":"肝病特異性較 AST 高。"},
    {"code":"09027C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["ALP", "Alk-P", "鹼性磷酯酶"],
     "freq":"依臨床需要；骨/膽汁鬱積追蹤",
     "freq_days":90,
     "icd":["K83","M85","M88","C79.5"],
     "icd_desc":"膽汁鬱積、骨病變、骨轉移"},
    {"code":"09031C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["γ-GT", "GGT", "gamma-GT", "麩胺轉酸脢"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["K70","K83","K76"],
     "icd_desc":"酒精性肝病、膽道疾病、膽汁鬱積",
     "clinical":"可鑑別 ALP 來源（肝 vs 骨）。"},
    {"code":"09029C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["T-Bil", "Total Bilirubin", "膽紅素總量", "總膽紅素"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["R17","K70","K80","K83","B18"],
     "icd_desc":"黃疸、肝病、膽石症、慢性肝炎"},
    {"code":"09030C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["D-Bil", "Direct Bilirubin", "直接膽紅素"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["R17","K70","K80","K83"],
     "icd_desc":"黃疸鑑別（直接性為肝後性）"},
    {"code":"09038C", "cat":"lab", "sub":"生化 / 肝功能",
     "aliases":["Alb", "Albumin", "白蛋白"],
     "freq":"慢性肝病、腎病 每 3-6 個月",
     "freq_days":90,
     "icd":["K70","K74","N18","R64","N04"],
     "icd_desc":"肝硬化、CKD、腎病症候群、營養不良"},

    # ============== LAB — 生化：其他 ==============
    {"code":"09017C", "cat":"lab", "sub":"生化 / 胰臟",
     "aliases":["Amylase", "血清澱粉脢", "澱粉脢", "血澱粉酶"],
     "freq":"急性腹痛鑑別 / 胰臟炎追蹤",
     "freq_days":30,
     "icd":["K85","K86","R10"],
     "icd_desc":"急/慢性胰臟炎、腹痛"},
    {"code":"09064C", "cat":"lab", "sub":"生化 / 胰臟",
     "aliases":["Lipase", "解脂酶"],
     "freq":"急性胰臟炎診斷/追蹤",
     "freq_days":30,
     "icd":["K85","K86"],
     "icd_desc":"急性胰臟炎 (較 Amylase 特異性高)"},
    {"code":"09032C", "cat":"lab", "sub":"生化 / 心臟",
     "aliases":["CPK", "CK", "肌酸磷化脢", "肌酸激酶"],
     "freq":"橫紋肌溶解、Statin 引起肌病變追蹤",
     "freq_days":30,
     "icd":["M62.82","T79.6","G71"],
     "icd_desc":"橫紋肌溶解、肌病變、Statin 副作用"},
    {"code":"09098B", "cat":"lab", "sub":"生化 / 心臟",
     "aliases":["Troponin T", "TnT", "心肌旋轉蛋白T"],
     "freq":"急性冠心症評估",
     "freq_days":1,
     "icd":["I20","I21","I24","R07"],
     "icd_desc":"急性冠心症、胸痛評估"},
    {"code":"09099C", "cat":"lab", "sub":"生化 / 心臟",
     "aliases":["Troponin I", "TnI", "心肌旋轉蛋白I"],
     "freq":"急性冠心症評估",
     "freq_days":1,
     "icd":["I20","I21","I24","R07"],
     "icd_desc":"急性冠心症、胸痛評估"},

    # ============== LAB — 血液 ==============
    {"code":"08011C", "cat":"lab", "sub":"血液 / CBC",
     "aliases":["CBC", "CBC I", "全套血液檢查 I", "八項"],
     "freq":"慢性病 每 3-6 個月；急性依需要",
     "freq_days":90,
     "icd":["D50","D64","D69","B18","N18","E11","J18","R50"],
     "icd_desc":"貧血、血小板異常、感染、慢性病、化療追蹤",
     "clinical":"含 WBC、RBC、Hb、Hct、Plt、MCV、MCH、MCHC。"},
    {"code":"08012C", "cat":"lab", "sub":"血液 / CBC",
     "aliases":["CBC II", "全套血液檢查 II", "七項"],
     "freq":"慢性病追蹤",
     "freq_days":90,
     "icd":["D50","D64","B18","N18","E11"],
     "icd_desc":"簡化版 CBC；多數診所常用"},
    {"code":"08013C", "cat":"lab", "sub":"血液 / CBC",
     "aliases":["DC", "WBC DC", "白血球分類", "Differential count"],
     "freq":"感染、血液病依需要",
     "freq_days":90,
     "icd":["R50","D72","B18","C81"],
     "icd_desc":"感染鑑別、白血球異常"},
    {"code":"08005C", "cat":"lab", "sub":"血液 / 發炎",
     "aliases":["ESR", "Sed rate", "紅血球沈降速度", "血沉"],
     "freq":"風濕免疫追蹤 每 1-3 個月",
     "freq_days":30,
     "icd":["M06","M05","M32","M31.5","M35"],
     "icd_desc":"類風濕、紅斑狼瘡、巨細胞動脈炎"},
    {"code":"12123C", "cat":"lab", "sub":"血液 / 發炎",
     "aliases":["CRP", "C-Reactive Protein", "C-反應蛋白"],
     "freq":"感染、發炎性疾病追蹤",
     "freq_days":30,
     "icd":["R50","M06","M32","J18","L03","K50"],
     "icd_desc":"感染、蜂窩性組織炎、類風濕、發炎性腸病"},
    {"code":"08026C", "cat":"lab", "sub":"血液 / 凝血",
     "aliases":["PT", "INR", "Prothrombin Time", "凝血酶原時間"],
     "freq":"Warfarin 使用 每 1-4 週；肝病每 3 個月",
     "freq_days":14,
     "icd":["I48","I26","I82","Z79.01","K70","K74"],
     "icd_desc":"AF 抗凝、VTE、肝硬化",
     "clinical":"DOACs 不需常規監測 INR。"},
    {"code":"08036C", "cat":"lab", "sub":"血液 / 凝血",
     "aliases":["aPTT", "APTT", "PTT", "部分凝血活酶時間"],
     "freq":"Heparin 使用 每日",
     "freq_days":1,
     "icd":["D68","I26","Z79.02"],
     "icd_desc":"UFH 抗凝、凝血因子缺乏、不明出血"},

    # ============== LAB — 內分泌：甲狀腺 ==============
    {"code":"09112C", "cat":"lab", "sub":"內分泌 / 甲狀腺",
     "aliases":["TSH", "甲狀腺刺激素", "甲促素"],
     "freq":"甲狀腺疾病調藥期 每 6-8 週；穩定每 6 個月",
     "freq_days":60,
     "icd":["E03","E05","E06","E07","E89.0"],
     "icd_desc":"甲狀腺低下、亢進、橋本氏、葛瑞夫茲、術後"},
    {"code":"09106C", "cat":"lab", "sub":"內分泌 / 甲狀腺",
     "aliases":["Free T4", "FT4", "游離甲狀腺素"],
     "freq":"與 TSH 併行",
     "freq_days":60,
     "icd":["E03","E05","E06","E07"],
     "icd_desc":"甲狀腺功能評估"},
    {"code":"09107C", "cat":"lab", "sub":"內分泌 / 甲狀腺",
     "aliases":["Free T3", "FT3", "游離三碘甲狀腺素"],
     "freq":"甲亢治療追蹤",
     "freq_days":60,
     "icd":["E05","E06.1"],
     "icd_desc":"甲狀腺亢進（T3-dominant 型）"},

    # ============== LAB — 尿液 ==============
    {"code":"06012C", "cat":"lab", "sub":"尿液",
     "aliases":["U/A", "Urinalysis", "尿液一般檢查", "尿常規"],
     "freq":"慢性病 每 3-6 個月；急性症狀依需要",
     "freq_days":90,
     "icd":["N39","N10","N18","E11","I10","R30","N20"],
     "icd_desc":"泌尿道感染、血尿、蛋白尿、糖尿病、結石",
     "clinical":"含蛋白、糖、潛血、酮體、亞硝酸、白血球酯酶等 11 項。"},
    {"code":"06013C", "cat":"lab", "sub":"尿液",
     "aliases":["U-Biochem", "尿生化", "尿液生化檢查"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["N39","N10","N18","E11"],
     "icd_desc":"泌尿/腎病輔助診斷"},
    {"code":"12111C", "cat":"lab", "sub":"尿液 / 糖尿病",
     "aliases":["UACR", "ACR", "Microalbumin", "尿液微量白蛋白", "微白蛋白"],
     "freq":"糖尿病 每年 1 次篩檢",
     "freq_days":365,
     "icd":["E11","E10","E13","I10"],
     "icd_desc":"糖尿病腎病篩檢、高血壓腎損評估",
     "clinical":"第二型糖尿病確診即應篩檢；第一型 5 年後開始。"},

    # ============== LAB — 病毒/感染 ==============
    {"code":"14032C", "cat":"lab", "sub":"感染 / 肝炎",
     "aliases":["HBsAg", "Ｂ型肝炎表面抗原", "B肝表面抗原"],
     "freq":"篩檢 1 次；慢性 B 肝每 6 個月追蹤",
     "freq_days":180,
     "icd":["B18.1","Z22.5","Z11.59"],
     "icd_desc":"慢性 B 肝、帶原者、篩檢",
     "clinical":"45-79 歲終生 1 次公費肝炎篩檢（B+C）。"},
    {"code":"14033C", "cat":"lab", "sub":"感染 / 肝炎",
     "aliases":["Anti-HBs", "HBsAb", "B肝表面抗體"],
     "freq":"疫苗接種追蹤、暴露後評估",
     "freq_days":365,
     "icd":["Z23","Z24","Z22.5"],
     "icd_desc":"B 肝免疫力評估、疫苗接種"},
    {"code":"14037C", "cat":"lab", "sub":"感染 / 肝炎",
     "aliases":["Anti-HBc", "HBcAb", "B肝核心抗體"],
     "freq":"輸血前、DAA/化療前評估",
     "freq_days":365,
     "icd":["B18.1","Z22.5","Z11.59"],
     "icd_desc":"B 肝感染史評估"},
    {"code":"14051C", "cat":"lab", "sub":"感染 / 肝炎",
     "aliases":["Anti-HCV", "HCV Ab", "C肝抗體"],
     "freq":"篩檢 1 次；高風險族群每年",
     "freq_days":365,
     "icd":["B18.2","B19.2","Z11.59"],
     "icd_desc":"慢性 C 肝、篩檢",
     "clinical":"陽性需 HCV RNA 確認。"},
    {"code":"13018C", "cat":"lab", "sub":"感染 / 消化",
     "aliases":["HP test", "幽門桿菌", "Helicobacter pylori"],
     "freq":"消化性潰瘍、胃炎評估",
     "freq_days":180,
     "icd":["K25","K26","K29","K30"],
     "icd_desc":"消化性潰瘍、慢性胃炎、功能性消化不良"},

    # ============== LAB — 糞便 ==============
    {"code":"09134C", "cat":"lab", "sub":"癌症篩檢",
     "aliases":["FIT", "iFOBT", "糞便潛血免疫分析", "免疫法糞便潛血"],
     "freq":"臨床診斷 1 次；公費篩檢 50-74 歲每 2 年",
     "freq_days":180,
     "icd":["K92.1","K62.5","R19.5"],
     "icd_desc":"下消化道出血評估（臨床診斷用）"},
    {"code":"07009C", "cat":"lab", "sub":"糞便",
     "aliases":["Stool Routine", "糞便一般檢查", "大便常規"],
     "freq":"急性腹瀉、感染評估",
     "freq_days":30,
     "icd":["A09","K52","K59"],
     "icd_desc":"急性腸胃炎、腹瀉、腸道感染"},

    # ============== LAB — 腫瘤標記 ==============
    {"code":"27052C", "cat":"lab", "sub":"腫瘤標記",
     "aliases":["PSA", "攝護腺特異抗原"],
     "freq":"BPH/攝護腺癌追蹤 每 6-12 個月",
     "freq_days":180,
     "icd":["C61","N40","R97.2"],
     "icd_desc":"攝護腺癌、BPH 追蹤",
     "clinical":"健康篩檢 PSA 健保不給付；有症狀/家族史可納。"},

    # ============== IMAGING — X 光 ==============
    {"code":"32001C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["CXR", "Chest X-ray", "胸腔 X 光", "胸部 X 光"],
     "freq":"依臨床需要",
     "freq_days":30,
     "icd":["J18","J44","I50","A15","R05","R06","J45"],
     "icd_desc":"肺炎、COPD、心衰竭、疑似結核、咳嗽、呼吸困難、氣喘"},
    {"code":"32002C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["CXR 加照", "胸腔加照"],
     "freq":"同次就診加照另一角度",
     "freq_days":1,
     "icd":["J18","J44","I50","A15"],
     "icd_desc":"胸腔多角度檢查",
     "clinical":"與 32001C 同日申報用於雙向或側位。"},
    {"code":"32007C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["KUB", "腹部 X 光", "Abdominal X-ray"],
     "freq":"依臨床需要",
     "freq_days":7,
     "icd":["R10","K56","N20","R19.11"],
     "icd_desc":"腹痛、腸阻塞、尿路結石"},
    {"code":"32011C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["Spine X-ray", "脊椎 X 光", "腰椎 X 光", "頸椎 X 光", "L-spine", "C-spine"],
     "freq":"慢性疼痛、外傷、退化追蹤",
     "freq_days":180,
     "icd":["M54","M51","M48","M50","S12","S22","S32"],
     "icd_desc":"下背痛、頸痛、椎間盤病變、脊椎骨折、退化"},
    {"code":"32013C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["Shoulder X-ray", "肩部 X 光"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["M75","S42","M19"],
     "icd_desc":"肩痛、旋轉肌袖疾患、肩骨折、退化"},
    {"code":"32015C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["Upper limb X-ray", "上肢 X 光", "手 X 光", "前臂 X 光"],
     "freq":"依臨床需要",
     "freq_days":30,
     "icd":["S52","S62","M19","M25"],
     "icd_desc":"上肢骨折、關節退化、關節痛"},
    {"code":"32017C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["Lower limb X-ray", "下肢 X 光", "膝 X 光", "腳 X 光", "Knee X-ray"],
     "freq":"退化性關節炎追蹤 每 1-2 年",
     "freq_days":365,
     "icd":["M17","S82","S83","M22","M23","S92"],
     "icd_desc":"膝/踝骨折、退化性關節炎、半月板、髕骨"},
    {"code":"32022C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["Pelvis X-ray", "骨盆 X 光", "Hip X-ray", "髖 X 光"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["M16","S72","S32","M25"],
     "icd_desc":"髖關節退化、髖骨折、骨盆外傷"},
    {"code":"32009C", "cat":"imaging", "sub":"影像 / X 光",
     "aliases":["Skull X-ray", "頭顱 X 光"],
     "freq":"依臨床需要",
     "freq_days":30,
     "icd":["S02","S06","R51"],
     "icd_desc":"頭部外傷、頭骨骨折"},

    # ============== IMAGING — 超音波 ==============
    {"code":"19001C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Abd US", "腹部超音波", "肝膽胰脾腎超音波"],
     "freq":"慢性肝病追蹤 每 6 個月；一般依需要",
     "freq_days":180,
     "icd":["K70","K74","B18","K80","K81","R10","C22","N28"],
     "icd_desc":"慢性肝炎、肝硬化、肝癌篩檢、膽石症、腹痛",
     "eligibility":"cert",
     "elig_desc":"執行醫師需具超音波專業訓練認證",
     "clinical":"B/C 肝追蹤 建議每 6 個月 US + AFP。"},
    {"code":"19009C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Abd US follow-up", "腹部超音波追蹤"],
     "freq":"慢性病追蹤性超音波",
     "freq_days":180,
     "icd":["K70","K74","B18","C22"],
     "icd_desc":"慢性肝病、腹部腫瘤追蹤",
     "eligibility":"cert",
     "elig_desc":"同腹部超音波；為追蹤性 (點數較低)"},
    {"code":"19012C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Thyroid US", "Neck US", "甲狀腺超音波", "頸部超音波", "副甲狀腺超音波"],
     "freq":"甲狀腺結節追蹤 每 6-12 個月",
     "freq_days":180,
     "icd":["E04","E05","E06","C73","D34","E21"],
     "icd_desc":"甲狀腺結節、腫大、亢進/低下、癌、副甲狀腺",
     "eligibility":"cert",
     "elig_desc":"執行醫師需具超音波專業訓練認證"},
    {"code":"19014C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Breast US", "乳房超音波"],
     "freq":"乳房病灶追蹤 每 6-12 個月",
     "freq_days":180,
     "icd":["N63","N60","C50","D24"],
     "icd_desc":"乳房腫塊、纖維囊腫、乳癌追蹤",
     "eligibility":"cert",
     "elig_desc":"執行醫師需具超音波專業訓練認證"},
    {"code":"19003C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Pelvic US", "婦科超音波", "Gyn US"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["N83","N80","N81","N92","D25"],
     "icd_desc":"卵巢囊腫、子宮肌瘤、子宮內膜異位、異常出血",
     "eligibility":"cert"},
    {"code":"19005C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["其他超音波", "Other US", "盆腔軟組織 US"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["R22","N83","R19","M79"],
     "icd_desc":"腹/盆腔外部位、軟組織腫塊等",
     "eligibility":"cert"},
    {"code":"19015C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Scrotal US", "陰囊超音波", "男性外生殖器超音波"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["N44","N45","N43","C62"],
     "icd_desc":"陰囊腫塊、睪丸扭轉、附睪炎、精索靜脈曲張",
     "eligibility":"cert"},
    {"code":"19016C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["MSK US", "肌肉骨骼超音波", "四肢超音波"],
     "freq":"依臨床需要",
     "freq_days":90,
     "icd":["M75","M77","M25","S86","M79"],
     "icd_desc":"肌腱炎、韌帶傷、軟組織腫塊、關節積液",
     "eligibility":"cert"},
    {"code":"19004C", "cat":"imaging", "sub":"影像 / 超音波",
     "aliases":["Sinus US", "鼻竇超音波"],
     "freq":"依臨床需要",
     "freq_days":30,
     "icd":["J01","J32","J33"],
     "icd_desc":"鼻竇炎、鼻瘜肉",
     "eligibility":"cert"},
    {"code":"18005C", "cat":"imaging", "sub":"影像 / 心臟超音波",
     "aliases":["Echo", "Echocardiogram", "心臟超音波", "心超", "超音波心臟圖"],
     "freq":"心衰竭、瓣膜病追蹤 每 6-12 個月",
     "freq_days":180,
     "icd":["I50","I35","I42","I11","I25","I48"],
     "icd_desc":"心衰竭、瓣膜、心肌病、HHD、心律不整",
     "eligibility":"cert",
     "elig_desc":"執行醫師需具心臟超音波訓練認證"},

    # ============== IMAGING — ECG ==============
    {"code":"18001C", "cat":"imaging", "sub":"影像 / 心電圖",
     "aliases":["ECG", "EKG", "12-lead ECG", "心電圖", "12導程心電圖"],
     "freq":"胸痛、心悸、心臟病追蹤依需要",
     "freq_days":30,
     "icd":["I20","I21","I48","I50","R07","R00","Z01.810"],
     "icd_desc":"冠心病、心梗、AF、心衰竭、胸痛、心悸、術前"},
    {"code":"18019C", "cat":"imaging", "sub":"影像 / 心電圖",
     "aliases":["Holter", "24hr ECG", "攜帶式心電圖", "Holter monitor"],
     "freq":"心律不整評估依需要",
     "freq_days":180,
     "icd":["I48","I49","R00","R55"],
     "icd_desc":"陣發性心悸、不明暈厥、AF 篩檢"},
    {"code":"18036B", "cat":"imaging", "sub":"影像 / 心電圖",
     "aliases":["HRV", "心跳變異", "Heart Rate Variability"],
     "freq":"自律神經評估",
     "freq_days":90,
     "icd":["G90","F45"],
     "icd_desc":"自律神經失調"},

    # ============== PROCEDURE — 傷口處理 ==============
    {"code":"48001C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["淺部創傷 <5cm", "淺部縫合 <5cm", "Superficial wound <5cm", "Suture <5cm"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S11","S21","S31","S41","S51","S61","S71","S81","S91","T14"],
     "icd_desc":"各部位淺層撕裂傷",
     "clinical":"含縫合。傷口處置與縫合屬同一代碼群。"},
    {"code":"48002C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["淺部創傷 5-10cm", "Superficial wound 5-10cm"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S11","S21","S31","S41","S51","S61","S71","S81","S91"],
     "icd_desc":"中型淺層撕裂傷"},
    {"code":"48003C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["淺部創傷 >10cm"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S11","S21","S31","S41","S51","S61","S71","S81","S91"],
     "icd_desc":"大型淺層撕裂傷"},
    {"code":"48004C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["深部複雜創傷 <5cm", "深部縫合 <5cm", "Deep wound <5cm"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S11","S21","S31","S41","S51","S61","S71","S81","S91"],
     "icd_desc":"傷口深達皮下組織、筋膜、肌肉；需分層縫合",
     "clinical":"病歷需明確記錄深度、層次、縫合方式。"},
    {"code":"48005C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["深部複雜創傷 5-10cm", "深部縫合 5-10cm"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S11","S21","S31","S41","S51","S61","S71","S81","S91"],
     "icd_desc":"中型深部複雜創傷"},
    {"code":"48006C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["深部複雜創傷 >10cm", "深部縫合 >10cm"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S11","S21","S31","S41","S51","S61","S71","S81","S91"],
     "icd_desc":"大型深部複雜創傷"},
    {"code":"48022C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["臉部創傷 <5cm", "Facial wound <5cm", "臉部縫合"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["S01","S00"],
     "icd_desc":"臉部淺層創傷"},
    {"code":"48010C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["傷口處置", "Wound care"],
     "freq":"每次就診 1 次",
     "freq_days":1,
     "icd":["T81","L08","L02"],
     "icd_desc":"術後傷口、其他傷口一般處置"},
    {"code":"48011C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["小換藥", "<10cm 換藥", "Small dressing"],
     "freq":"每次就診 1 次",
     "freq_days":1,
     "icd":["L08","L02","T81","L89"],
     "icd_desc":"<10cm 傷口換藥、褥瘡"},
    {"code":"48012C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["中換藥", "10-20cm 換藥"],
     "freq":"每次就診 1 次",
     "freq_days":1,
     "icd":["L08","L02","T81","L89"],
     "icd_desc":"10-20cm 傷口換藥"},
    {"code":"48013C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["大換藥", ">20cm 換藥"],
     "freq":"每次就診 1 次",
     "freq_days":1,
     "icd":["L08","L02","T81","L89"],
     "icd_desc":">20cm 傷口換藥"},
    {"code":"48025C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["拆線 <10cm", "Suture removal <10cm"],
     "freq":"術後 7-14 天",
     "freq_days":1,
     "icd":["Z48"],
     "icd_desc":"術後拆線"},
    {"code":"48026C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["拆線 >10cm", "Suture removal >10cm"],
     "freq":"術後 7-14 天",
     "freq_days":1,
     "icd":["Z48"],
     "icd_desc":"術後大傷口拆線"},
    {"code":"48007C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["膿瘍切開", "I&D", "Abscess drainage"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["L02","L03","L04"],
     "icd_desc":"皮膚膿瘍、蜂窩性組織炎併膿瘍"},
    {"code":"48008C", "cat":"procedure", "sub":"處置 / 傷口",
     "aliases":["填塞排膿"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["L02","L03","T81"],
     "icd_desc":"膿瘍引流、傷口填塞"},

    # ============== PROCEDURE — 注射 ==============
    {"code":"39003C", "cat":"procedure", "sub":"處置 / 注射",
     "aliases":["IM injection", "生物學藥劑注射", "肌肉注射", "皮下注射", "疫苗注射"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["多種"],
     "icd_desc":"依藥品臨床適應症",
     "clinical":"含反應試驗注射。藥品另計。"},
    {"code":"39004C", "cat":"procedure", "sub":"處置 / 注射",
     "aliases":["IV drip", "點滴", "大量液體點滴", "IV fluid"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["R11","E86","A09","R50"],
     "icd_desc":"脫水、嘔吐、腹瀉、發燒需靜脈補液",
     "clinical":"N/S、D5W、Lactated Ringer's 等；輸注液另計。"},
    {"code":"39005C", "cat":"procedure", "sub":"處置 / 注射",
     "aliases":["關節腔內注射", "Intra-articular injection"],
     "freq":"退化性關節炎 每 6 個月",
     "freq_days":180,
     "icd":["M17","M19","M25.5"],
     "icd_desc":"退化性膝關節炎、關節炎、關節積液",
     "clinical":"含玻尿酸注射、類固醇關節注射。"},
    {"code":"39018C", "cat":"procedure", "sub":"處置 / 注射",
     "aliases":["肌腱注射", "Tendon injection"],
     "freq":"肌腱炎痛點治療",
     "freq_days":30,
     "icd":["M65","M67","M75","M77"],
     "icd_desc":"肌腱炎、板機指、網球肘、高爾夫球肘"},
    {"code":"39024B", "cat":"procedure", "sub":"處置 / 注射",
     "aliases":["激痛點注射", "Trigger point injection", "TP injection"],
     "freq":"每痛點單獨計；依臨床需要",
     "freq_days":30,
     "icd":["M79.1","M79.7"],
     "icd_desc":"肌筋膜疼痛、纖維肌痛"},

    # ============== PROCEDURE — 呼吸 ==============
    {"code":"57021C", "cat":"procedure", "sub":"處置 / 呼吸",
     "aliases":["噴霧治療", "Nebulizer", "蒸氣吸入", "霧化吸入"],
     "freq":"每次就診 1 次",
     "freq_days":1,
     "icd":["J45","J44","J20","J06","J40","J21"],
     "icd_desc":"氣喘發作、COPD 急性惡化、支氣管炎、上呼吸道感染痙攣",
     "clinical":"藥品（Berotec/Atrovent/Combivent/Pulmicort）另計。"},
    {"code":"57003C", "cat":"procedure", "sub":"處置 / 呼吸",
     "aliases":["氧氣吸入 每小時", "Oxygen therapy"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["J96","R06","I50","J44"],
     "icd_desc":"急性缺氧、呼吸衰竭、心衰竭、COPD"},

    # ============== PROCEDURE — 耳鼻喉 ==============
    {"code":"54024C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["鼻腔沖洗", "Nasal irrigation", "鼻沖洗", "洗鼻", "鼻腔灌洗"],
     "freq":"依臨床需要，每次就診 1 次",
     "freq_days":1,
     "icd":["J00","J01","J30","J31","J32","J33","J34.2","J34.3"],
     "icd_desc":"急性鼻咽炎、鼻竇炎、過敏性鼻炎、鼻瘜肉",
     "clinical":"生理食鹽水沖洗鼻腔/鼻竇引流分泌物。"},
    {"code":"54019C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["耳鼻喉膿痂取出", "鼻腔抽吸", "分泌物抽吸"],
     "freq":"每次就診 1 次",
     "freq_days":1,
     "icd":["J00","J01","J30","J31","J32","J06","H60","H65"],
     "icd_desc":"鼻炎、鼻竇炎、上呼吸道感染、外耳道/中耳炎分泌物",
     "clinical":"耳鼻喉局部治療 - 膿或痂皮之取出或抽吸。"},
    {"code":"54010C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["鼻前部鼻流血處理", "前鼻出血處置", "Anterior epistaxis"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["R04.0"],
     "icd_desc":"鼻出血"},
    {"code":"54013C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["鼻內電燒術", "鼻出血電燒", "Nasal cautery"],
     "freq":"反覆鼻出血依需要",
     "freq_days":90,
     "icd":["R04.0"],
     "icd_desc":"反覆鼻出血"},
    {"code":"54021C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["鼻填塞(前側)", "前鼻填塞", "Anterior packing"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["R04.0"],
     "icd_desc":"鼻出血填塞"},
    {"code":"54001C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["耳垢嵌塞取出", "挖耳屎", "Cerumen removal"],
     "freq":"依臨床需要 (通常每側獨立計)",
     "freq_days":90,
     "icd":["H61.2"],
     "icd_desc":"耳垢嵌塞、耳道阻塞"},
    {"code":"54035C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["耳道沖洗", "Ear irrigation"],
     "freq":"依臨床需要",
     "freq_days":30,
     "icd":["H61.2","H60"],
     "icd_desc":"耳垢、外耳道清潔"},
    {"code":"54036C", "cat":"procedure", "sub":"處置 / 耳鼻喉",
     "aliases":["鼓室穿刺", "Tympanocentesis"],
     "freq":"依臨床需要",
     "freq_days":7,
     "icd":["H66","H65"],
     "icd_desc":"中耳炎併積液抽吸"},

    # ============== PROCEDURE — 導尿 ==============
    {"code":"47013C", "cat":"procedure", "sub":"處置 / 泌尿",
     "aliases":["一般導尿", "Catheterization", "導尿"],
     "freq":"依臨床需要",
     "freq_days":1,
     "icd":["R33","N40"],
     "icd_desc":"急性尿滯留、BPH"},
    {"code":"47014C", "cat":"procedure", "sub":"處置 / 泌尿",
     "aliases":["留置導尿", "Foley catheter", "尿管留置"],
     "freq":"依臨床需要",
     "freq_days":30,
     "icd":["R33","N40","N31"],
     "icd_desc":"尿滯留、神經性膀胱"},

    # ============== PROCEDURE — 論質計酬 (P4P) ==============
    {"code":"P1407C", "cat":"procedure", "sub":"論質計酬 / 糖尿病",
     "aliases":["DM P4P 新收案", "糖尿病照護網新收案"],
     "freq":"新收案一次",
     "freq_days":365,
     "icd":["E10","E11","E13","E14"],
     "icd_desc":"加入糖尿病論質計酬第一階段之新案",
     "eligibility":"p4p",
     "elig_desc":"需先加入「糖尿病醫療給付改善方案」；未加入者僅能申報一般檢驗代碼"},
    {"code":"P1408C", "cat":"procedure", "sub":"論質計酬 / 糖尿病",
     "aliases":["DM P4P 追蹤", "糖尿病照護追蹤"],
     "freq":"第一階段追蹤 每 3 個月",
     "freq_days":90,
     "icd":["E10","E11","E13","E14"],
     "icd_desc":"加入糖尿病論質計酬第一階段之追蹤照護",
     "eligibility":"p4p",
     "elig_desc":"需先加入糖尿病論質計酬計畫"},
    {"code":"P1409C", "cat":"procedure", "sub":"論質計酬 / 糖尿病",
     "aliases":["DM P4P 年度評估"],
     "freq":"每年 1 次",
     "freq_days":365,
     "icd":["E10","E11","E13","E14"],
     "icd_desc":"糖尿病第一階段年度評估 (含眼底、足部檢查等)",
     "eligibility":"p4p",
     "elig_desc":"需先加入糖尿病論質計酬計畫"},
    {"code":"P1410C", "cat":"procedure", "sub":"論質計酬 / 糖尿病",
     "aliases":["DM P4P 第二階段追蹤"],
     "freq":"第二階段每 3 個月",
     "freq_days":90,
     "icd":["E10","E11","E13","E14"],
     "icd_desc":"糖尿病第二階段追蹤",
     "eligibility":"p4p"},
    {"code":"P4301C", "cat":"procedure", "sub":"論質計酬 / CKD",
     "aliases":["CKD P4P 新收案", "初期慢性腎臟病新收案"],
     "freq":"新收案一次",
     "freq_days":365,
     "icd":["N18.1","N18.2","N18.3"],
     "icd_desc":"初期慢性腎臟病 (Stage 1-3) 新收案",
     "eligibility":"p4p",
     "elig_desc":"需先加入「初期慢性腎臟病醫療給付改善方案」"},
    {"code":"P4302C", "cat":"procedure", "sub":"論質計酬 / CKD",
     "aliases":["CKD P4P 追蹤"],
     "freq":"每 3 個月",
     "freq_days":90,
     "icd":["N18.1","N18.2","N18.3"],
     "icd_desc":"初期慢性腎臟病追蹤管理",
     "eligibility":"p4p"},
    {"code":"P1612C", "cat":"procedure", "sub":"論質計酬 / 氣喘",
     "aliases":["氣喘 P4P 新收案"],
     "freq":"新收案一次",
     "freq_days":365,
     "icd":["J45"],
     "icd_desc":"氣喘論質計酬新收案",
     "eligibility":"p4p",
     "elig_desc":"需先加入氣喘醫療給付改善方案"},
    {"code":"P1613C", "cat":"procedure", "sub":"論質計酬 / 氣喘",
     "aliases":["氣喘 P4P 追蹤"],
     "freq":"每 3 個月",
     "freq_days":90,
     "icd":["J45"],
     "icd_desc":"氣喘追蹤管理",
     "eligibility":"p4p"},
    {"code":"P6011C", "cat":"procedure", "sub":"論質計酬 / COPD",
     "aliases":["COPD P4P 新收案"],
     "freq":"新收案一次",
     "freq_days":365,
     "icd":["J44"],
     "icd_desc":"COPD 論質計酬新收案",
     "eligibility":"p4p"},
    {"code":"P6012C", "cat":"procedure", "sub":"論質計酬 / COPD",
     "aliases":["COPD P4P 追蹤"],
     "freq":"每 3 個月",
     "freq_days":90,
     "icd":["J44"],
     "icd_desc":"COPD 追蹤管理",
     "eligibility":"p4p"},
    {"code":"P4201C", "cat":"procedure", "sub":"論質計酬 / C肝",
     "aliases":["C肝 P4P 新收案"],
     "freq":"新收案一次",
     "freq_days":365,
     "icd":["B18.2","B19.2"],
     "icd_desc":"全民健保肝炎醫療給付改善方案新收案",
     "eligibility":"p4p"},
    {"code":"P7001C", "cat":"procedure", "sub":"論質計酬 / DM+CKD",
     "aliases":["DM 合併 CKD P4P 追蹤"],
     "freq":"每 3 個月",
     "freq_days":90,
     "icd":["N18","E11"],
     "icd_desc":"糖尿病合併初期慢性腎臟病",
     "eligibility":"p4p"},

    # ============== PROCEDURE — 戒菸 (E-prefix) ==============
    {"code":"E1022C", "cat":"procedure", "sub":"衛教 / 戒菸",
     "aliases":["戒菸衛教費", "戒菸衛教", "Smoking cessation education"],
     "freq":"戒菸療程中依需要",
     "freq_days":7,
     "icd":["F17","Z72.0"],
     "icd_desc":"尼古丁依賴、吸菸行為",
     "eligibility":"cert",
     "elig_desc":"醫師需完成二代戒菸治療認證課程；機構需簽約"},
    {"code":"E1027C", "cat":"procedure", "sub":"衛教 / 戒菸",
     "aliases":["戒菸服務診察費"],
     "freq":"戒菸門診就診",
     "freq_days":7,
     "icd":["F17","Z72.0"],
     "icd_desc":"戒菸門診",
     "eligibility":"cert",
     "elig_desc":"需具戒菸認證醫師與簽約機構"},
    {"code":"E1023C", "cat":"procedure", "sub":"衛教 / 戒菸",
     "aliases":["戒菸 3 個月追蹤-治療"],
     "freq":"戒菸治療 3 個月追蹤",
     "freq_days":90,
     "icd":["F17","Z72.0"],
     "icd_desc":"戒菸治療三個月後追蹤",
     "eligibility":"cert"},

    # ============== PROCEDURE — 預防保健 (公費) ==============
    {"code":"21", "cat":"procedure", "sub":"預防保健",
     "aliases":["成健 40-64 歲", "成人預防保健"],
     "freq":"40-64 歲每 3 年 1 次",
     "freq_days":1095,
     "icd":["Z00","Z13"],
     "icd_desc":"成人預防保健",
     "eligibility":"program",
     "elig_desc":"機構需與國健署簽約；每 3 年 1 次（年齡符合）",
     "clinical":"含血糖、血脂、肝腎、尿液、BMI、BP、憂鬱/菸酒檢測。"},
    {"code":"22", "cat":"procedure", "sub":"預防保健",
     "aliases":["成健 65 歲以上"],
     "freq":"65 歲以上每年 1 次",
     "freq_days":365,
     "icd":["Z00","Z13"],
     "icd_desc":"老人預防保健",
     "eligibility":"program",
     "elig_desc":"機構需與國健署簽約；每年 1 次（年齡符合）"},

    # ============== LAB — 健康檢查/其他 ==============
    {"code":"85", "cat":"lab", "sub":"癌症篩檢",
     "aliases":["定量 FIT", "定量免疫法糞便潛血", "大腸癌篩檢"],
     "freq":"50-74 歲每 2 年 1 次（公費）",
     "freq_days":730,
     "icd":["Z12.11"],
     "icd_desc":"大腸癌篩檢（公費）",
     "eligibility":"program",
     "elig_desc":"機構需與國健署簽約大腸癌篩檢"},
]


def main():
    # Build code → CSV row map
    code_map = {}
    with open(CSV_PATH, encoding='utf-8-sig') as f:
        for row in csv.DictReader(f):
            code_map[row['診療項目代碼'].strip()] = row

    items = []
    missing = []
    for c in CURATED:
        code = c['code']
        if code not in code_map:
            missing.append(code)
            continue
        row = code_map[code]
        try:
            pts = int(row['健保支付點數'])
        except Exception:
            pts = 0

        # Normalize CSV 中文名 (remove stray full-width brackets etc.)
        name_zh = row['中文項目名稱'].strip()
        # Use a cleaner short name for display: take up to first 、 or （ or 全形 (
        short_zh = re.split(r'[，。,（(]', name_zh, maxsplit=1)[0].strip()
        if len(short_zh) < 4:  # don't over-shorten
            short_zh = name_zh[:30]

        notes_parts = []
        csv_note = (row.get('備註') or '').strip()
        if csv_note:
            notes_parts.append(f"【健保署備註】{csv_note[:500]}")
        if c.get('clinical'):
            notes_parts.append(f"【臨床說明】{c['clinical']}")
        notes = "\n".join(notes_parts) if notes_parts else ''

        item = {
            "id": code,
            "code": code,
            "name_zh": short_zh,
            "name_zh_full": name_zh,
            "name_en": (row.get('英文項目名稱') or '').strip(),
            "aliases": c.get('aliases', []),
            "category": c['cat'],
            "subcategory": c['sub'],
            "points": pts,
            "frequency": c['freq'],
            "frequency_days": c['freq_days'],
            "indications": c.get('icd', []),
            "indication_desc": c.get('icd_desc', ''),
            "notes": notes,
            "eligibility": c.get('eligibility', 'default'),
            "eligibility_desc": c.get('elig_desc', ''),
            "effective_date": row.get('生效起日', ''),
            "source_url": "https://info.nhi.gov.tw/INAE5000/INAE5001S01",
        }
        items.append(item)

    # Diagnoses: 保留 (cross-reference updated with new codes)
    diagnoses = [
        {"icd":"E11", "name_zh":"第二型糖尿病", "name_en":"Type 2 Diabetes Mellitus",
         "aliases":["DM type 2","T2DM"],
         "common_tests":["09005C","09140C","09006C","09002C","09015C","12111C","09001C","09004C","09043C","09044C","06012C","09026C","P1407C","P1408C"],
         "key_rules":"HbA1c 每 3 個月 1 次；尿液微量白蛋白每年 1 次；lipid profile 每 3-6 個月；納入 DM P4P 另有 P1407/P1408 照護費。"},
        {"icd":"I10", "name_zh":"原發性高血壓", "name_en":"Essential hypertension",
         "aliases":["HTN","高血壓"],
         "common_tests":["09002C","09015C","09021C","09022C","06012C","18001C","09001C","09004C","12111C"],
         "key_rules":"每 6-12 個月追蹤電解質、腎功能、尿液；ECG 視需要。註：高血壓目前無單獨 P4P 方案。"},
        {"icd":"E78", "name_zh":"高血脂症", "name_en":"Hyperlipidemia",
         "aliases":["HLD","Dyslipidemia"],
         "common_tests":["09001C","09004C","09043C","09044C","09025C","09026C","09032C"],
         "key_rules":"Lipid profile 每 3-6 個月；Statin 起始 3 個月內追蹤 AST/ALT 與 CK。"},
        {"icd":"B18.1", "name_zh":"慢性 B 型肝炎", "name_en":"Chronic Hepatitis B",
         "aliases":["慢性B肝","HBV"],
         "common_tests":["09025C","09026C","09029C","08011C","08026C","19001C","14032C","14086C"],
         "key_rules":"每 3-6 個月追蹤 AST/ALT；每 6 個月 HBV DNA + AFP + 腹部超音波 (肝癌監測)。"},
        {"icd":"N18", "name_zh":"慢性腎臟病", "name_en":"Chronic Kidney Disease (CKD)",
         "aliases":["CKD","慢性腎病"],
         "common_tests":["09002C","09015C","09013C","09021C","09022C","06012C","12111C","08012C","09038C","P4301C","P4302C"],
         "key_rules":"CKD 1-2 每 6 個月；3a 每 3-6 月；3b-4 每 3 月；5 每 1-3 月。初期 CKD 論質計酬 P4301C/P4302C。"},
        {"icd":"E03", "name_zh":"甲狀腺低下", "name_en":"Hypothyroidism",
         "aliases":["Hypothyroid"],
         "common_tests":["09112C","09106C","09001C","09004C"],
         "key_rules":"Levothyroxine 調藥期 TSH 每 6-8 週；穩定每 6-12 個月。"},
        {"icd":"I48", "name_zh":"心房顫動", "name_en":"Atrial Fibrillation",
         "aliases":["AF","Afib"],
         "common_tests":["18001C","18019C","08026C","09015C","18005C","09112C"],
         "key_rules":"Warfarin 使用者 PT/INR 每 4 週穩定；DOAC 年度腎功能。初發 AF 需 TSH + Echo。"},
        {"icd":"J45", "name_zh":"氣喘", "name_en":"Asthma",
         "aliases":["Asthma"],
         "common_tests":["32001C","57021C","P1612C","P1613C"],
         "key_rules":"急性發作噴霧治療；納入氣喘 P4P 有 P1612/P1613 照護費。"},
        {"icd":"J44", "name_zh":"COPD", "name_en":"Chronic Obstructive Pulmonary Disease",
         "aliases":["COPD"],
         "common_tests":["32001C","57021C","P6011C","P6012C"],
         "key_rules":"急性惡化噴霧治療；納入 COPD P4P 有 P6011/P6012 照護費。"},
    ]

    data = {
        "meta": {
            "version": "2.0.0",
            "updated_at": "2026-04-20",
            "source": "健保署 115.04.01 官方支付標準代碼表",
            "source_file": "A21030000I-D20021-001.csv",
            "disclaimer": "本資料以健保署 115.04.01 官方公告為準；實際申報請於 info.nhi.gov.tw/INAE5000/INAE5001S01 查核最新版本。",
            "eligibility_default": "診斷符合 + 頻率在規定內即可申報（無需加入特殊計畫）",
            "eligibility_legend": {
                "default": "診斷符合 + 頻率在規定內即可申報",
                "p4p": "需加入論質計酬計畫才能申報（照護費類）",
                "cert": "需醫師具特定訓練認證",
                "program": "需該機構與健保署/國健署簽約之公費計畫",
                "prior": "需事前審查 / 事前報備"
            }
        },
        "items": items,
        "diagnoses": diagnoses,
    }

    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f"✓ 寫入 {OUT}")
    print(f"  items: {len(items)}  diagnoses: {len(diagnoses)}")
    if missing:
        print(f"\n⚠ CSV 查無代碼：{missing}")


if __name__ == "__main__":
    main()
